version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=erayaraz
    restart: always

  micrometer_example:
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - prometheus
